//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeepingYaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCheckin
    {
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int EmployeeId { get; set; }
        public int WorkingHours { get; set; }
        public string Note { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
    }
}
