//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeepingYaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DailyCheckins = new HashSet<DailyCheckin>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StatusCode { get; set; }
    
        public virtual ICollection<DailyCheckin> DailyCheckins { get; set; }
    }
}
